/** @type {import('jest').Config} */
module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    roots: ['<rootDir>/test'],
    testMatch: ['**/*.test.ts'],
    // src/config.ts is generated by configure.js and is not in the repository
    resolver: '<rootDir>/test/config-resolver.js',
    clearMocks: true
};
